export const SAMPLE_TODOS = [
  {
    id: 1,
    task_title: "Morning Yoga & Meditation 🧘‍♀️",
    category: "Personal",
    categoryVariant: "personal",
  },
  {
    id: 2,
    task_title: "Team standup prep",
    category: "Work",
    categoryVariant: "work",
  },
  {
    id: 3,
    task_title: "Laundry & kitchen reset",
    category: "Chores",
    categoryVariant: "chores",
  },
  {
    id: 4,
    task_title: "Read one chapter",
    category: "Growth",
    categoryVariant: "growth",
  },
  {
    id: 5,
    task_title: "Call mum ☎️",
    category: "Family",
    categoryVariant: "family",
  },
  {
    id: 6,
    task_title: "Invoice follow-ups",
    category: "Side Hustle",
    categoryVariant: "sideHustle",
  },
  {
    id: 7,
    task_title: "Sketch app wireframes",
    category: "Work",
    categoryVariant: "work",
  },
  {
    id: 8,
    task_title: "Book dentist appointment",
    category: "Health",
    categoryVariant: "health",
  },
  {
    id: 9,
    task_title: "Fix mobile navbar spacing",
    category: "Work",
    categoryVariant: "work",
  },
  {
    id: 10,
    task_title: "Evening cycling 🚴",
    category: "Fitness",
    categoryVariant: "fitness",
  },
  {
    id: 11,
    task_title: "Pay electricity bill",
    category: "Finance",
    categoryVariant: "finance",
  },
  {
    id: 12,
    task_title: "Clean workspace setup",
    category: "Chores",
    categoryVariant: "chores",
  },
  {
    id: 13,
    task_title: "Practice React hooks",
    category: "Growth",
    categoryVariant: "growth",
  },
  {
    id: 14,
    task_title: "Reply to client emails",
    category: "Work",
    categoryVariant: "work",
  },
  {
    id: 15,
    task_title: "Meal prep for tomorrow 🍱",
    category: "Personal",
    categoryVariant: "personal",
  },
  {
    id: 16,
    task_title: "Research SaaS competitors",
    category: "Side Hustle",
    categoryVariant: "sideHustle",
  },
  {
    id: 17,
    task_title: "Water indoor plants 🌱",
    category: "Home",
    categoryVariant: "home",
  },
  {
    id: 18,
    task_title: "Push latest commits to GitHub",
    category: "Work",
    categoryVariant: "work",
  },
  {
    id: 19,
    task_title: "Watch system design video",
    category: "Growth",
    categoryVariant: "growth",
  },
  {
    id: 20,
    task_title: "Weekly budget review",
    category: "Finance",
    categoryVariant: "finance",
  },
  {
    id: 21,
    task_title: "Grocery shopping 🛒",
    category: "Home",
    categoryVariant: "home",
  },
  {
    id: 22,
    task_title: "Update portfolio website",
    category: "Work",
    categoryVariant: "work",
  },
  {
    id: 23,
    task_title: "Stretching routine",
    category: "Fitness",
    categoryVariant: "fitness",
  },
  {
    id: 24,
    task_title: "Backup laptop files",
    category: "Tech",
    categoryVariant: "tech",
  },
  {
    id: 25,
    task_title: "Brainstorm YouTube content ideas",
    category: "Side Hustle",
    categoryVariant: "sideHustle",
  },
  {
    id: 26,
    task_title: "Deep clean bathroom",
    category: "Chores",
    categoryVariant: "chores",
  },
  {
    id: 27,
    task_title: "Read API documentation",
    category: "Growth",
    categoryVariant: "growth",
  },
  {
    id: 28,
    task_title: "Family dinner planning 🍽️",
    category: "Family",
    categoryVariant: "family",
  },
  {
    id: 29,
    task_title: "Morning run",
    category: "Fitness",
    categoryVariant: "fitness",
  },
  {
    id: 30,
    task_title: "Refactor sidebar component",
    category: "Work",
    categoryVariant: "work",
  },
];
